sudo: true
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq build-essential gettext python-dev zlib1g-dev libpq-dev xvfb
  - sudo apt-get install -qq libtiff4-dev libjpeg8-dev libfreetype6-dev liblcms1-dev libwebp-dev
  - sudo apt-get install -qq graphviz-dev python-setuptools python3-dev python-virtualenv python-pip
  - sudo apt-get install -qq firefox automake libtool libreadline6 libreadline6-dev libreadline-dev
  - sudo apt-get install -qq libsqlite3-dev libxml2 libxml2-dev libssl-dev libbz2-dev wget curl llvm
language: python
python:
  - "3.6.3"
services:
  - postgresql
env:
  - DJANGO_SETTINGS_MODULE=config.settings.test
    DATABASE_URL=postgres://postgres@localhost/test_db
    DJANGO_AWS_STORAGE_BUCKET_NAME=peacegeeks-pathways-static
    DJANGO_AWS_ACCESS_KEY_ID=Foo
    DJANGO_AWS_SECRET_ACCESS_KEY=Bar
    DJANGO_SECRET_KEY=Baz
    DJANGO_SENTRY_DSN=Ban
install:
  - pip install -r requirements/test.txt
before_script:
  - psql -c 'create database test_db;' -U postgres
script:
  - python manage.py migrate
  - python manage.py test
