# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-01 00:35
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_homepage'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogindexpage',
            name='intro',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True),
        ),
    ]
